name: test actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: dhanu
      - name: log  greet time
        run: echo "${{ steps.greet.outputs.time}}"
